---

#
# Ensure user_id is defined
#
- hosts: all
  tasks:
    - name: Assert that user_id is defined when running as root
      assert:
        msg: 'user_id must be defined when running as root (missing --extra-vars "user-id=USER"?)'
        that:
          - user_id is defined
      when: ansible_facts['user_id'] == "root"

    - name: Register user_id
      set_fact:
        user_id: "{{ ansible_user_id }}"
      when: ansible_facts['user_id'] != "root"


#
# Generate mirrorlist
#
- hosts: all
  roles:
    - mirrorlist
  tags: always

#
# Create main user and aur_builder
#

- hosts: all
  tasks:
    - import_role:
        name: user
      when: ansible_facts['user_id'] == "root"

    - name: Get user home directory
      changed_when: false
      register: getent
      shell: "getent passwd {{ user_id }} | awk -F: '{ print $6 }'"

    - name: Register user_id
      set_fact:
        user_home: "{{ getent.stdout }}"

    - user:
        group: wheel
        name: aur_builder
        system: yes
  tags: always

#
# Set up sudo so aur_builder can run pacman without password
#
- hosts: all
  roles:
    - sudo
  tags: always

#
# Install terminals
#

- hosts: all
  roles:
    - alacritty
  tags:
    - alacritty
    - desktop

#
# Install bspwm
#
- hosts: all
  roles:
    - bspwm
  tags:
    - desktop
    - bspwm

#
# Chromium
#
- hosts: all
  roles:
    - chromium
  tags:
    - chromium
    - browsers

#
# Firefox
#
- hosts: all
  roles:
    - firefox
  tags:
    - firefox
    - browsers
    - desktop

#
#
#
- hosts: all
  roles:
    - fonts
  tags:
    - fonts

#
# Lastpass-cli
#
- hosts: all
  roles:
    - lastpass-cli
  tags:
    - lastpass

#
# Lastpass
#
#- hosts: all
#  roles: [ lastpass ]
#  tags:
#    - lastpass

#
# Cheat-sheet
#
- hosts: all
  roles:
    - cht-sh
  tags:
    - cht-sh

#
# Cli - utils
#
- hosts: all
  roles:
    - cli-utilities
  tags:
    - cli-utilities

#
# Dunst - notifications
#
- hosts: all
  roles:
    - dunst
  tags:
    - dunst

#
# LightDM
#
- hosts: all
  roles:
    - lightdm
  tags:
    - lightdm
    - desktop

#
# Openbox
#
#- hosts: all
#  roles:
#    - openbox
#  tags:
#    - openbox

#
# NeoVim
#
- hosts: all
  roles:
    - neovim
  tags:
    - editor
    - neovim

#
# VS Code
#
- hosts: all
  roles:
    - vscode
  tags:
    - editor
    - vscode

#
# Neofetch
#
- hosts: all
  roles:
    - neofetch
  tags:
    - neofetch

#
# picom
#
- hosts: all
  roles:
    - picom
  tags:
    - picom
    - desktop

#
# Polybar
#
- hosts: all
  roles:
    - polybar
  tags:
    - polybar
    - desktop

#
# Rofi - application launcher
#
- hosts: all
  roles:
    - rofi
  tags:
    - rofi
    - desktop

#
# Sound
#
- hosts: all
  roles:
    - sound
  tags:
    - sound
    - desktop

#
# Spotify
#
- hosts: all
  roles:
    - spotify
  tags:
    - spotify

#
# SXHKD
#
- hosts: all
  roles:
    - sxhkd
  tags:
    - desktop
    - sxhkd

#
# vifm
#
- hosts: all
  roles:
    - vifm
  tags:
    - vifm

#
# SDKMan
#
- hosts: all
  roles:
    - sdkman
  tags:
    - develop
    - sdkman

#
# Jetbrains
#
- hosts: all
  roles:
    - jetbrains-toolbox
  tags:
    - develop
    - jetbrains

#
# NodeVersionManager
#
- hosts: all
  roles:
    - nvm
  tags:
    - develop
    - node
#
# QuteBrowser
#

- hosts: all
  roles:
    - qutebrowser
  tags:
    - qutebrowser
#
# Rust
#
- hosts: all
  roles:
    - rust
  tags:
    - develop
    - rust

#
# xdg-user-dirs
#
- hosts: all
  roles:
    - xdg-user-dirs
  tags:
    - desktop
    - xdg-user-dirs

#
# xorg
#
- hosts: all
  roles:
    - xorg
  tags:
    - desktop
    - xorg

#
# Zathura
#
- hosts: all
  roles:
    - zathura
  tags:
    - zathura

#
# Zsh
#
- hosts: all
  roles:
    - zsh
  tags:
    - zsh
